### ISSUE TITLE
Cambiar el 100vw

### ISSUE THREAD

**Issue by ortizlucas** [MariaO-code/capacitacion-react#3]
https://github.com/MariaO-code/capacitacion-react/blob/61f6bbaba749a87047174bb74cd8f31ac382f1c2/proyecto-react/src/components/header/style.scss#L6

Por alguna razon ese 100vw está rompiendo, cambialo a 100% y si va a tener un border en los costados agregale un box-sizing: border-box; para que no salga el scroll horizontal.

**Comment by MariaEOcampo** [comment]
Ahi lo ví Lucas, y si, era mejor con 100%. Gracias!
